// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Highlighter
{
    internal sealed partial class Vsix
    {
        public const string Id = "QuadSpinner.Highlighter.4b62";
        public const string Name = "Highlighter";
        public const string Description = @"An arbitrary highlighter that lets you pick individual class, parameter, or other element names to highlight across your projects. It makes it easier to find and identify objects inside your project. You can also use it for comment annotations, dividers, and more.";
        public const string Language = "en-US";
        public const string Version = "1.0.1.10";
        public const string Author = "Dax Pandhi";
        public const string Tags = "C#,Highlighting,Productivity,Color,Keyword,VB,CSS,HTML,Colorize,Tags,Mark";
    }
}
