// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Highlighter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HighlighterString = "e6f482eb-859f-4dab-928c-fbd2f0201cbb";
        public static Guid Highlighter = new Guid(HighlighterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MenuGroup = 0x0001;
        public const int CreateHighlight = 0x0100;
    }
}